use_frameworks!
source 'https://gitee.com/hongtuedu/Spec.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'HTLFSpec_Example' do
  pod 'HTLFSpec', :path => '../'

  target 'HTLFSpec_Tests' do
    inherit! :search_paths

	pod 'HTETools'
  	pod 'Masonry'
    	pod 'FBSnapshotTestCase'
  end
end
